[project]
name = "pvm"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=5.4.1",
    "faker>=33.0.0",
    "fastexcel>=0.12.0",
    "gcsfs>=2024.10.0",
    "ibis-framework[duckdb,examples,polars,snowflake,sqlite,visualization]>=9.5.0",
    "ipykernel>=6.29.5",
    "jupyterlab>=4.3.0",
    "mkdocs-jupyter>=0.25.1",
    "mkdocstrings-python>=2.0.0",
    "mypy>=1.14.0",
    "pins>=0.8.6",
    "polars>=1.12.0",
    "pygments>=2.18.0",
    "pygraphviz>=1.14",
    "pyperclip>=1.9.0",
    "pyright>=1.1.389",
    "pytest-cov>=6.0.0",
    "pytest>=8.3.3",
    "ruff>=0.7.3",
    "ty>=0.0.1a29",
]

[project.scripts]
hello = "pvm:hello"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Same as Black.
line-length = 120
indent-width = 4

# Assume Python 3.8
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "W", "C90", "I", "N", "D", "UP", "YTT", "ANN", "ASYNC", "S", "FBT", "B", "A", "COM", "C4", "FA", "ISC", "INP", "PL", "SIM", "RET", "ARG", "PERF"]
ignore = ["ANN101", "D203", "D212", "D213", "ISC001", "COM812"]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.per-file-ignores]
"docs/notebooks/*" = ["INP001"]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
docstring-code-format = true

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = 80

exclude = ["ANN101", "D203", "D212"]


[tool.ty.src]
include = ["src"]
exclude = ["**/node_modules",
    "**/__pycache__",
    "src/experimental",
    "src/typestubs",
    "src/pvm/charts.py", "src/pvm/calculations.py", "src/formulas.py", "tests"
]

[[tool.mypy.overrides]]
module = ["ibis.*", "graphviz.*"]
follow_untyped_imports = true

[[tool.mypy.overrides]]
module = ["pvm.common.observable_list"]
disable_error_code = ["override", "misc"]
